title: Amber Wang / 王婆
description: 米闪工作室主理人（videomaker）

social:

  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:btbr403@gmail.com

avatar: /assets/images/avatar.png
introduction: >
  Hi! 我是米闪工作室主理人Amber.<br/>
  2013年与我好友兼老公一起开始了米闪工作室。<br/>
  做一些没用又好玩的硬件小装置。


working:
  title: Working Experience
  timeline:
    - date: Now
    - "Slow Dance"
    - date: 2016-04
    - "Pixel Stick"

education:
  title: Public Management
  timeline:
    - date: 2010-07
    - "Bachelor of Jiangsu University of Science and Technology: Public Management"
