title: Amber Wang / 王婆
description: 工作在七牛云的市场小兵，业余打理米闪工作室。

social:

  - title: Facebook
    img: /assets/images/facebook.png
    url: https://www.facebook.com/amber.wang.161214

  - title: Gmail
    img: /assets/images/gmail.png
    url: mailto:btbr403@gmail.com

avatar: /assets/images/avatar.png
introduction: >
  Hi! 我是米闪工作室主理人Amber.<br/>
  2013年与我好友/老公孙浩钦一起开始了米闪工作室。<br/>
  做一些没用又好玩的硬件小装置、航拍旅行。


working:
  title: Projects
  timeline:
    - date: Now
    - "Slow Dance Project"
    - date: 2016-12
    - "Trip to Koh Phangan(drone footage) 100K view on Facebook"
    - date: 2015-04
    - "Pixel Stick-light painting tool"
